telerik/xaml-docs

- sdk-examples.md
- section_508_compliance.md
> Made Section 508 article hidden.

- controls/radrichtextbox/features/fields-and-document-variables/fields.md
TOC, TC, PageRef fields descriptions updated.
> Updated/added some fields descriptions.

- controls/radrichtextbox/document-elements/annotations/features-manipulating-annotations.md
DocumentSelection also has methods for retrieving annotations.
> Updated Annotations article.

- controls/raddesktopalert/how-to/apply-multiple-animations-for-showing-and-hiding-raddesktopalert.md
Add article that explains how to apply multiple animations for showing and hiding RadDesktopAlert
> Add article that explains how to apply multiple animations

- controls/radscheduleview/features/resources.md
Changed line 31, First of all, let's set a __ResourceTypesCollection__:  to First of all, let's set a __ResourceTypesSource__:
> Fixed incorrect instruction

- installation-and-deployment/deploying-telerik-ui/distributing-telerik-assemblies.md
- installation-and-deployment/deploying-telerik-ui/protecting-telerik-assembly.md
> Updated information about distributing Telerik assembies

- controls/radrichtextbox/features/headers-and-footers.md
Updated and enumerated code-snippets, style changes
> RadRichTextBox: Updated Headers and Footers article

- controls/radgridview/columns/frozen-columns.md
* Added necessary colons
* Added VB example for using the FrozenColumnsChanged event
> [GridView] Updated FrozenColumnsChanged event article

- controls/touchmanager/getting-started.md
Ignore the name of the Branch :) I create a new one called Q1-2016 by mistake and copied the GreenTheme_Updates branch in it :)
> Green theme articles update

- controls/radgridview/events/delete.md
Made clear when the Deleting event gets triggered
> GridView: Delete events lifecycle update

- controls/radgridview/clipboard/copying.md
Enumerated examples
Added anchor links
Added see also section
Small refactors
> [GridView] Refactored Copying article

- controls/radgridview/filtering/faq/popup-stays.md
Added **ShouldCloseFilteringPopupOnKeyboardFocusChanged** to "Filtering Popup Remains Opened" FAQ article
> [GridView] Documented ShouldCloseFilteringPopupOnKeyboardFocusChanged

- controls/raddataform/features/customize-commands.md
-Applied some slight changes related to Erik`s comments on a similar section (RadCollectionNavigator commands customizations)
> -dataform - customize commands refactored

- styling-and-appearance/styling-apperance-implicit-styles-overview.md
Replaced code snippets in Styling Custom Control section
Added VB.NET example
> Refactored Styling Custom Controls section of Setting a Theme article

- _assets/javascripts/app.js
- _assets/stylesheets/styles.css
- _plugins/kendo_grid_generator.rb
FIXED => No Selection Color in ListBox with Files
FIXED => First file should be selected on load
FIXED => Folders are listed among with files in some examples (check diagram OrgChart)
FIXED => Code word is seen until the first select file is loaded - remove the code word
FIXED => When you click on example link, it would be better to open in new page
FIXED => When you hover with mouse over a file (e.g. MainWindow.xaml), we can change the mouse cursor 
> Dev Focused Examples articles KendoGrid Fixes

- controls/radspellchecker/features/multilanguage-support.md
Fixed header in RadSpellChecker Multilanguage support.
> Fixed header in Multilanguage support

- controls/radgridview/features/managing-data-validation.md
-Added section for ValidationType property
> Grid view differentiate errors

- _assets/javascripts/app.js
- _assets/stylesheets/styles.css
- _plugins/kendo_grid_generator.rb
--Api rate message added for IE (when user exceeds 60 requests per hour)
--KendoUI grid style fixes
> KendoGrid fixes + IE msg ApiRate

- controls/radpropertygrid/changes-and-backward-compatibility/backward-compatibility.md
- controls/radpropertygrid/features/selection.md
Update Backward Compatibility article
> [PropertyGrid] Remove SelectedField and SelectedFieldChanged from Selection article

- controls/radgridview/export/faq.md
Change link to invalid printing example.
> Update printing article.

- controls/radcloudupload/features/adding-files-programmatically.md
> minor copy edits but check comments

- _plugins/kendo_grid_generator.rb
Fix typo in the Kendo grid generator.
> Fix typo in the Kendo grid generator

- controls/radspreadsheet/unsupported-features.md
Data visualization is renamed to Charts.
> Update Unsupported features article

- controls/radrichtextbox/events-overview.md
Add description for property affecting DocumentContentChanged event.
> Update RadRichTextBox Events Overview

- controls/raddocking/how-to/disable-tab-navigation.md
Please review the comment at the beginning for technical accuracy.
> copy editing with one comment to review

- controls/radganttview/features/scrolling.md
> copy editing with several comments to review

- controls/radpdfviewer/customization-and-extensibility/customize-pdf-rendering.md
- controls/radpdfviewer/unsupported-features.md
Added captions for code snippets
> PdfViewer: Updated content to add links to an SDK example

- controls/radimageeditor/events.md
- controls/radimageeditor/features/commands-and-tools.md
- controls/radimageeditor/features/history.md
- controls/radimageeditor/features/import-export.md
- controls/radimageeditor/features/radimageeditorui.md
- controls/radimageeditor/getting-started.md
- controls/radimageeditor/how-to/howto-custom-tool.md
- controls/radimageeditor/how-to/implement-drawtoolbase.md
- controls/radimageeditor/how-to/implement-toolbase.md
- controls/radimageeditor/localization.md
- controls/radimageeditor/tools/drawing.md
- controls/radimageeditor/tools/howto-use-crop.md
- controls/radimageeditor/tools/shape-tool.md
Renamed regions, added See Also sections and several small fixes in articles
> ImageEditor: Updated code snippets, refactored articles

- _config.yml
- controls/radrichtextbox/features/clipboard-support.md
- controls/radrichtextbox/features/code-block.md
- controls/radrichtextbox/features/commands.md
- controls/radrichtextbox/features/comments.md
- controls/radrichtextbox/features/document-elements-bookmarks.md
- controls/radrichtextbox/features/document-elements-hyperlink.md
- controls/radrichtextbox/features/document-protection.md
- controls/radrichtextbox/features/headers-and-footers.md
- controls/radrichtextbox/features/history.md
- controls/radrichtextbox/features/positioning.md
- controls/radrichtextbox/features/raddocumenteditor.md
- controls/radrichtextbox/features/read-only-ranges.md
- controls/radrichtextbox/features/repeat-table-header-row.md
- controls/radrichtextbox/features/search.md
- controls/radrichtextbox/features/section-columns.md
- controls/radrichtextbox/features/selection.md
- controls/radrichtextbox/features/spellcheck.md
- controls/radrichtextbox/features/track-changes.md
- controls/radrichtextbox/features/watermark.md
Now the articles are in alphabetical order
> RichTextBox: Reordered articles in the Features folder

- controls/radgridview/features/ui-virtualization.md
-removed section for disabling UI Virtualization
-advised not to work with the visual elements
> -RadGridView UI Virtualization Refactor

- controls/radtreelistview/radtreeliestview-getting-started.md
> TreeListView - HomogenousDataMoreNoticeable

- web.config
> Common - RewriteRedirectRules

- controls/raddiagram/features/global-settings.md
> Diagram: Global Settings article update

- controls/radchartview3d/axes.md
- controls/radchartview3d/camera.md
- controls/radchartview3d/features/behaviors/camerabehavior.md
- controls/radchartview3d/features/chart-grid.md
- controls/radchartview3d/getting-started.md
- controls/radchartview3d/series/barseries3d.md
- controls/radchartview3d/series/pointseries3d.md
- controls/radchartview3d/series/surfaceseries3d.md
- controls/radchartview3d/styles-and-templates/cutomizing-3d-series.md
> ChartView3D: Copy edit changes

- controls/radmaskedinput/features/common.md
> MaskedInput: Add TextBoxStyle property description

- controls/raddiagram/features/raddiagrams-commands.md
- controls/raddiagram/howto/raddiagrams-override-command.md
> Diagram: New how-to article added - Override Diagram Command

- controls/radribbonview/features/ribbon-controls/applicationmenu.md
> RibbonView: Update in the Application Menu article

- controls/radchart/overview.md
> Small update of RadChart overview

- upgrade-api-analyzer-sl.md
- upgrade-api-analyzer.md
Copyeditor's suggestions applied
> Update Upgrade API Analyzer article

- controls/radcollectionnavigator/collectionnavigator_key-properties.md
- controls/radcollectionnavigator/collectionnavigator_visual_struture.md
Document ButtonsStyle property
Document CommandButtonsVisibility property
> [CollectionNavigator] Add Key Properties Article

- controls/radchartview/features/labels/label-definition.md
> spelling mistake on "mechanism"

- controls/raddiagram/howto/customize-path-pencil-tools.md
Refactor Customize Path and Pencil Tools article for RadDiagram
The examples are enumerated, some wording is changed
> Refactor Customize Path and Pencil Tools article

- controls/radtimeline/features/formatter-provider.md
- controls/radtimeline/features/intervals-formatters.md
Added links to the related articles
> Update formatter-related articles

- controls/radpdfviewer/ui/command-descriptors.md
The IsEnabled property had an incorrect spelling of its type.
> Corrected type for IsEnabled

- styling-and-appearance/stylemanager/common-styling-apperance-setting-theme-wpf.md
Fixed misspelling and one grammar problem
> Grammatical corrections

- controls/radpdfviewer/document-model/text/text-selection.md
Code snippets added, the existing ones are enumerated
Style changes
> Update the Text Selection topic for PdfViewer

- controls/radrichtextbox/features/headers-and-footers.md
It's not clear when different types of headers are applied.
> Update headers and footers article

- controls/radpivotgrid/getting-started/started-understanding-pivot.md
> Corrects typo in RadPivotGrid documentation

- _config.yml
- controls/radtreeview/how-to/drag-and-drop/cancel-drag-start.md
> TreeView: New Article - How to cancel drag start

- controls/radtreeview/features/feautres-treeviewitem-selection.md
> TreeView: Refactoring the Selection article

- controls/radrichtextbox/document-elements/features-paragraph.md
> Update Paragraph article

- controls/radpropertygrid/features/defining-propertysets.md
> [PropertyGrid] Document PropertySet property and UpdatePropertySetValue method

- controls/radrichtextbox/mef.md
Fixed sentence at opening of initial load performance section due to confusing grammar.
> Grammar fix

- controls/radrichtextbox/import-export/pdf/settings.md
Update the descriptions of all settings, added their default values and behaviors.
> Update PDF export settings

- _assets/stylesheets/styles.css
- _plugins/markdown_processor.rb
Fix anchors offset
Move edit button
> Update Feedback Form

- controls/radfiledialogs/radopenfiledialog.md
Update examples and description
> [FileDialogs] Document DereferenceLinks Property

- controls/radrichtextbox/document-elements/features-inlineuicontainer.md
Added rtf format provider behavior to the InlineUIContainer article.
> Rtf provider added to InlineUIContainer article

- controls/radrichtextbox/features/styles/list-styles.md
The Add method had incorrect parameter
> Fixed c# snippet for Step 3

- _layouts/index.html
- personal-data-collection.md
Added link to the script adding the cookie consent dialog.
> Added new article about personal data collection.

- controls/radchartview/indicators/indicators-overview.md
- controls/radchartview3d/getting-started.md
ChartView: Fixed a broken slug + changing the size of the Financial Indicators Overview picture
> ChartView3D: Added description about PlotAreaSize property.

- mvvm-helpers/common-converters.md
> Update EnumToVisibilityConverter information

- controls/radrichtextbox/features/search.md
- controls/radrichtextbox/import-export/features-data-providers.md
Formatting changes in Data Providers topic
> Update Search topic title

- controls/raddiagram/extensions/overview.md
- controls/raddiagram/extensions/toolbox.md
- controls/raddiagram/features/design-time-support.md
- controls/raddiagram/howto/customize-itemiformationadorner.md
- controls/raddocking/overview2.md
- getting-started/installation/installation-installing-from-MSI-wpf.md
- getting-started/installation/installation-installing-from-MSI.md
- getting-started/installation/installation-installing-which-file-do-i-need.md
- getting-started/installation/installation-system-requirements-wpf.md
- getting-started/installation/installation-system-requirements.md
- getting-started/installation/installing-wpf-demos.md
- getting-started/next-steps.md
- knowledge-base/kb-gridview-remove-search-cell-background.md
- upgrade/installation-upgrading-from-trial-to-developer-license-wpf.md
- upgrade/installation-upgrading-from-trial-to-developer-license.md
Slug fixes added.
Minor changes added.
> New KB added.

- controls/radchartview/radchartview-vs.-radchart.md
Just noticed a couple of issues while reading through the article.
> A few typo fixes

- controls/radcombobox/howto/how-to-align-to-the-left-the-text-of-the-comboboxitem-when-it-is-too-long2.md
The original read a little clunky.
> Clarify Combobox item left alignment article title

- controls/radtreeview/how-to/bind-selected-item.md
- web.config
Added note to use BasedOn property in NoXaml scenario
> Add note in Bind to a Selected Item article

- controls/raddatapager/how-to/change-page-size-dynamically.md
Added the edited control template for DataPagerPresenterTemplate
> DataPager: Updated code snippets in the Change PageSize dynamically article

- controls/radchartview/getting-started/introduction.md
Small fix to the xmlns syntax (the opening quote was in the wrong location).
> Update ChartView introduction.md

- controls/raddiagram/howto/customize-dragging.md
"private void OnPropertyChaged(string name)" and its references changed to "private void OnPropertyChanged(string name)".
> Fixed typo "Chaged" should be "Changed".

- controls/radsyntaxeditor/features/palettes.md
Reverts telerik/xaml-docs#2151
> Revert "Update SyntaxEditor Palettes doc with Office2019"

- controls/radslider/styling-and-appearance/styling-overview.md
> Common: Typo in RadSlider styling overview

- controls/raddiagram/overview.md
Fixing a typo. Changed 'richt' to 'rich'
> Update rad diagram overview.md file.

- controls/radgridview/rows/customizing-rows.md
- controls/radlayoutcontrol/features/edit-the-layout.md
- controls/radlayoutcontrol/features/save-load-layout.md
LayoutControl: Add information about the automatically created groups in the control
> GridView: Document the RowHeight property

- controls/radsyntaxeditor/features/find-replace.md
Note: Do not merge this request before the next internal build (2020.3.1109).
> SyntaxEditor: Document SearchPanelWidth

- controls/raddiagram/howto/raddiagrams-mvvm.md
Apparently, there was a linebreak missing.
> Add missing linebreak

- _pdf_silverlight.yml
- _silverlight.yml
Disable CTA Panel for Silverlight
> Disable CTA Panel for Silverlight

- getting-started/installation/installation-system-requirements-wpf.md
- integration/visual-studio-extensions/vs-extensions-overview.md
- integration/visual-studio-extensions/vs-extensions-toolbox-configurator.md
- netcore/overview.md
Updated the .NET Core article to speak about .NET 5 and 6 also.
> Add information about the VS2022 support.

- controls/radchartview/features/behaviors/panzoom.md
Feel free to close this pull request and fix (or not fix) the typo via other methods.
> Fix a tiny typo in panzoom.md

- knowledge-base/kb-buttons-distorted-or-pixelated-buttons.md
- knowledge-base/kb-property-grid-disable-horizontal-scrollbar.md
Documentation: add KB for distorted and pixelated buttons on Dell machines
Documentation: Disable HorizontalScrollBar Kb article
> KB articles

- controls/radrichtextbox/features/selection.md
Added new property for RadRichTextBox
> Added new property

- controls/radspreadsheet/features/ui-working-with-selection.md
> Changed obsolete collection

- controls/radrichtextbox/import-export/xaml/settings.md
- controls/radrichtextbox/import-export/xaml/xaml.md
- controls/radrichtextbox/import-export/xaml/xamlformatprovider.md
Added info about the new API in XamlFormatProvider
> Added info about the new API in XamlFormatProvider

- knowledge-base/kb-cardview-fix-group-changes.md
- knowledge-base/kb-changehandicon-to-loadingicon.md
Creating New KB Article for RadCardView refres and reapply GroupDescriptors.
> Creating new KB Article

- _assetsApi/docfx-tmpl/src/partials/footer.tmpl.partial
- _assetsApiSL/docfx-tmpl/src/partials/footer.tmpl.partial
- _config.yml
Integrated new feedback form in docs and api ref. Replaced sheetId with productCode.
> Integrate new feedback form and replace sheetId with productCode

- wpflab/smart-ai-components.md
> Hide article

- wpflab/smart-ai-components.md
> Make wpf lab visible
