telerik/xaml-docs

- controls/radrichtextbox/document-elements/features-inlineuicontainer.md
- controls/radrichtextbox/import-export/features-import-export-settings.md
Also enumerated examples and style changes in the Import/Export Settings and InlineUIContainer articles.
> RichTextbox: Removed unusable API

- controls/radziplibrary/features/zip-extensions.md
`DotNetPlatformManager` is moved to the end, as it's not important and in the general case users won't use it directly at all.
> Reorganized radziplibrary-zipextensions article.

- controls/radpdfviewer/customization-and-extensibility/customize-pdf-rendering.md
A note is added to dеscribe different approaches for decoding images with DCTDecode filter.
> Add information about overriding the DctDecode class in PdfViewer

- controls/radtreelistview/radtreeliestview-getting-started.md
The ItemsSource of the RadTreeListView and TreeListViewTableDefinition has to be set. It was unclear from the example that the ItemsSource of the RadTreeListView also had to be set.
> Added missing ItemsSources of the RadTreeListView

- controls/radgridview/columns/column-groups.md
TextBox does not make sense in the header template. TextBlock is the correct control to use to replace default the GridViewColumnGroup HeaderTemplate.
> Changing TextBox to TextBlock on GridViewColumnGroup HeaderTemplate

- controls/radrichtextbox/features/document-protection.md
The variable type can't be PermissionInfoCollection for a collection of UserInfo items.
> Wrong variable type in document protection article

- controls/radtreeview/how-to/drag-and-drop/implement-between-treeview-and-listbox.md
`e.Handled = true;` is required in order to convey items in payload. If not, the data with given keys `DraggedData`, `DropDetails` are not remained.
> fix example code.

- styling-and-appearance/styling-apperance-setting-a-theme-overview.md
It's useful to have link to the article with the available themes just at the beginning of this long article.
> Add link to Setting a Theme article

- controls/radrichtextbox/features/spellcheck.md
Describe that spell checker can run asynchronously in the background, and how to invalidate the currently processed words.
> Update spell checker docs

- controls/radpdfviewer/features/digital-signature.md
- controls/radpdfviewer/ui/find-dialog.md
Removed the note that you need to use RadPdfViewerToolBar to register the dialog through XAML. Added the XAML registration as a second method of registration of the dialog.
> Changed the sections about adding pdfviewer dialogs in two articles

- controls/radchart/features/format-expressions.md
Link to the DateTime formats was broken, points to the correct documentation now.
> Fixed a broken link

- controls/radtimebar/features/scrollmode.md
Just removed an extra letter from a single word: *Scroll~~I~~Only* -> *ScrollOnly*
> Small typo fix

- cloud-integration/amazon-web-services/overview.md
AWS SDK for .NET only has versions for VS 2013 or newer so it would make sense to mention that as the minimum version for following the tutorials.
> Changed minimum VS version requirement

- controls/radgridview/columns/columntypes/checkbox-column.md
see 
https://github.com/telerik/xaml-docs/issues/2014
I thought you cannot style GridViewCheckBoxColumn based on that last Infobox in the docs.
> clarify styling for GridViewCheckBoxColumn

- controls/raddiagram/features/diagram-layout.md
I came across this typo while reading the documentation
> Fix spelling of "once"

- controls/radlegend/overview.md
Originally had a header "Key Feautres." This branch has updated it to be "Key Features."
> Fixed typo on RadLegend overview.md

- controls/radwebcam/getting-started.md
Telerik.Windows.Controls.Navigation is needed on opening settings of RadWebCam.
> Add missing dependency

- controls/radgridview/sorting/custom.md
Hello 😄 I've noticed there is a typo in the comments about ascending sort: should be "ascending" instead of "none"
> Fix typo in comment

- controls/radtileview/features/fluid-content-control.md
Manual content changing must be done inside the event handler, 
it is not an example 3, its the same example
> Update misleading title

- getting-started/installation/nuget/troubleshooting.md
Replaced v2 URL and related guidance
> Update NuGet troubleshooting.md

- controls/radmap/features/providers/arcgis.md
- controls/radmap/features/providers/azuremapprovider.md
- controls/radmap/features/providers/bing-rest-map-provider/bing-map-rest.md
- controls/radmap/features/providers/mapboxprovider.md
- controls/radmap/features/providers/osm-provider.md
- controls/radmap/features/providers/providers.md
- Refactored the Providers Overview article and added information about missing providers
- Added a new article for the OSM provider
- Addea d section for each provider that uses third-party tile data for the attribution copyright label
> Map: Add attribution copyright information for providers
